namespace AutoMapperTest
{
    public class Class2
    {
        public string Property00 { get; set; }
        public string Property01 { get; set; }
        public string Property02 { get; set; }
        public string Property03 { get; set; }
        public string Property04 { get; set; }
        public string Property05 { get; set; }
        public string Property06 { get; set; }
        public string Property07 { get; set; }
        public string Property08 { get; set; }
        public string Property09 { get; set; }
        public string Property10 { get; set; }
        public string Property11 { get; set; }
        public string Property12 { get; set; }
        public string Property13 { get; set; }
        public string Property14 { get; set; }
        public string Property15 { get; set; }
        public string Property16 { get; set; }
        public string Property17 { get; set; }
        public string Property18 { get; set; }
        public string Property19 { get; set; }
        public string Property20 { get; set; }
        public string Property21 { get; set; }
        public string Property22 { get; set; }
        public string Property23 { get; set; }
        public string Property24 { get; set; }
        public string Property25 { get; set; }
        public string Property26 { get; set; }
        public string Property27 { get; set; }
        public string Property28 { get; set; }
        public string Property29 { get; set; }
        public string Property30 { get; set; }
        public string Property31 { get; set; }
        public string Property32 { get; set; }
        public string Property33 { get; set; }
        public string Property34 { get; set; }
        public string Property35 { get; set; }
        public string Property36 { get; set; }
        public string Property37 { get; set; }
        public string Property38 { get; set; }
        public string Property39 { get; set; }
        public string Property40 { get; set; }
        public string Property41 { get; set; }
        public string Property42 { get; set; }
        public string Property43 { get; set; }
        public string Property44 { get; set; }
        public string Property45 { get; set; }
        public string Property46 { get; set; }
        public string Property47 { get; set; }
        public string Property48 { get; set; }
        public string Property49 { get; set; }
        public string Property50 { get; set; }
        public string Property51 { get; set; }
        public string Property52 { get; set; }
        public string Property53 { get; set; }
        public string Property54 { get; set; }
        public string Property55 { get; set; }
        public string Property56 { get; set; }
        public string Property57 { get; set; }
        public string Property58 { get; set; }
        public string Property59 { get; set; }
        public string Property60 { get; set; }
        public string Property61 { get; set; }
        public string Property62 { get; set; }
        public string Property63 { get; set; }
        public string Property64 { get; set; }
        public string Property65 { get; set; }
        public string Property66 { get; set; }
        public string Property67 { get; set; }
        public string Property68 { get; set; }
        public string Property69 { get; set; }
        public string Property70 { get; set; }
        public string Property71 { get; set; }
        public string Property72 { get; set; }
        public string Property73 { get; set; }
        public string Property74 { get; set; }
        public string Property75 { get; set; }
        public string Property76 { get; set; }
        public string Property77 { get; set; }
        public string Property78 { get; set; }
        public string Property79 { get; set; }
        public string Property80 { get; set; }
        public string Property81 { get; set; }
        public string Property82 { get; set; }
        public string Property83 { get; set; }
        public string Property84 { get; set; }
        public string Property85 { get; set; }
        public string Property86 { get; set; }
        public string Property87 { get; set; }
        public string Property88 { get; set; }
        public string Property89 { get; set; }
        public string Property90 { get; set; }
        public string Property91 { get; set; }
        public string Property92 { get; set; }
        public string Property93 { get; set; }
        public string Property94 { get; set; }
        public string Property95 { get; set; }
        public string Property96 { get; set; }
        public string Property97 { get; set; }
        public string Property98 { get; set; }
        public string Property99 { get; set; }
    }
}